language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
notifications:
  irc: chat.freenode.net#bpilgrim
  email:
  recipients:
    - KlingmannM@gmail.com
  on_success: always
  on_failed: always
script:
  - nosetests tests
after_success:
 - coveralls