language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
before-install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-pygame
  - sudo apt-get install -qq python-pygame
notifications:
  irc: chat.freenode.net#bpilgrim
  email:
  recipients:
    - KlingmannM@gmail.com
  on_success: always
  on_failed: always
script:
  - nosetests tests
virtualenv:
  system_site_packages: true
after_success:
 - coveralls